//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassfishSubscriber.resource
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NonLocalizableResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NonLocalizableResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlassfishSubscriber.resource.NonLocalizableResource", typeof(NonLocalizableResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string with name [{0}] is not found in configuration file.
        /// </summary>
        internal static string DBConnectionStringNotFound {
            get {
                return ResourceManager.GetString("DBConnectionStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination [{0}] of type [{1}] found in configuration file is not supported.
        /// </summary>
        internal static string DestinationNotSupported {
            get {
                return ResourceManager.GetString("DestinationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception logged at UTC Time :[{0}]  Local Time:[{1}].
        /// </summary>
        internal static string ErrorLogTimeMessage {
            get {
                return ResourceManager.GetString("ErrorLogTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlassfishSubscriberServiceLog.
        /// </summary>
        internal static string EventlogName {
            get {
                return ResourceManager.GetString("EventlogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlassfishSubscriberService.
        /// </summary>
        internal static string EventlogSource {
            get {
                return ResourceManager.GetString("EventlogSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while checking if event log source exists.
        /// </summary>
        internal static string EventLogSourceCheckError {
            get {
                return ResourceManager.GetString("EventLogSourceCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed thread id [{0}].
        /// </summary>
        internal static string LogThreadInfoMessage {
            get {
                return ResourceManager.GetString("LogThreadInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message logged at UTC Time :[{0}]  Local Time:[{1}].
        /// </summary>
        internal static string LogTimeMessage {
            get {
                return ResourceManager.GetString("LogTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reply received after connect.
        /// </summary>
        internal static string NoConnectReply {
            get {
                return ResourceManager.GetString("NoConnectReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved [{0}] bytes of data at location [{1}].
        /// </summary>
        internal static string SavedFileLogMessage {
            get {
                return ResourceManager.GetString("SavedFileLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving [{0}] message(s) from destination [{1}].
        /// </summary>
        internal static string SavingMessageFromDestiantion {
            get {
                return ResourceManager.GetString("SavingMessageFromDestiantion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started GlassfishSubscriberService.
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while starting GlassfishSubscriberService.
        /// </summary>
        internal static string ServiceStartError {
            get {
                return ResourceManager.GetString("ServiceStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting GlassfishSubscriberService.
        /// </summary>
        internal static string ServiceStarting {
            get {
                return ResourceManager.GetString("ServiceStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while stopping GlassfishSubscriberService.
        /// </summary>
        internal static string ServiceStopError {
            get {
                return ResourceManager.GetString("ServiceStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped GlassfishSubscriberService.
        /// </summary>
        internal static string ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping GlassfishSubscriberService.
        /// </summary>
        internal static string ServiceStopping {
            get {
                return ResourceManager.GetString("ServiceStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StompClient is null, can not subscribe to destination.
        /// </summary>
        internal static string StompClientNullMessage {
            get {
                return ResourceManager.GetString("StompClientNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing to destination [{0}] of type [{1}].
        /// </summary>
        internal static string SubscribingToDestinationMessage {
            get {
                return ResourceManager.GetString("SubscribingToDestinationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning logged at UTC Time :[{0}]  Local Time:[{1}].
        /// </summary>
        internal static string WarningLogTimeMessage {
            get {
                return ResourceManager.GetString("WarningLogTimeMessage", resourceCulture);
            }
        }
    }
}
